### ISSUE TITLE
Add support for CEX.io

### ISSUE THREAD

**Issue by gcordalis** [chrisshiplet/btcbar#29]
Fantastic and simple tool as is, would love to see CEX.io support added as it's the exchange I use most.

**Comment by chrisshiplet** [comment]
I've had a super busy holiday season, but I have some bugfixes to do soon so I'll try and get this in! Thanks for the suggestion.

**Comment by chrisshiplet** [comment]
@gcordalis Sorry for the delay, this is in the latest release

**Comment by gcordalis** [comment]
Champion. Thanks so much!
