### ISSUE TITLE
add please www.bitcoin.com

### ISSUE THREAD

**Issue by foozzi** [chrisshiplet/btcbar#33]
add please www.bitcoin.com, i send you $5 in btc cash :)

**Comment by chrisshiplet** [comment]
Hi there, thanks for the suggestion. I personally don't use Bitcoin Cash, and I think it would be confusing to have tickers for two different currencies in the app's current UI. Feel free to fork the repo and make a Bitcoin Cash version though!

**Comment by foozzi** [comment]
no, you did not understand me, I meant to make a course on the site bitcoin.com, I will gladly make a trip to bitcoin or bitcoin cash))
couse i'm python,php,nodejs coder(

**Comment by chrisshiplet** [comment]
I'm not familiar with bitcoin.com or what a course is on that site, do you have any links with more information? I will look into it, but I can't promise anything because I'm super busy right now.
